### ISSUE TITLE
Jar file not working in Windows 8.1 with latest java installed.

### ISSUE THREAD

**Issue by ttaj** [crashinvaders/gdx-texture-packer-gui#10]
Hey as of late the latest available release of this doesn't seem to be working anymore. What ends up happening is that if I run it normally or use the command line, it opens but doesn't actually pop up the GUI.   I've tried to open up other jars and they work fine.  Here's what it looks like.

![image](https://cloud.githubusercontent.com/assets/6380809/23689494/abef549e-0380-11e7-81cf-5f6b59fda666.png)

In task manager it is using resources so clearly it's running. I also have the latest java installed and have already tried reinstalling this program.

**Comment by ttaj** [comment]
I sort of figured out why it's happening. Apparently if you try to press this 
![image](https://cloud.githubusercontent.com/assets/6380809/23699973/e4ae72ac-03b6-11e7-800b-9d8c88b25d18.png) Then the GUI will become unable to be shown unless you open up task manager and force it to be maximized.

So the real issue here is preventing the GUI from freaking out when that button is pressed.

**Comment by metaphore** [comment]
To be clear, do you get black window since application startup or upon "maximize" button click?

I just tried to reproduce this on Win8.1x64 virtual machine and it appears to work fine.

Could you please locate installation folder (`C:\Program Files (x86)\GdxTexturePacker` by default), run it from CMD (`java -jar gdx-texturepacker.jar`) and ensure that there is nothing suspicious in the output?

**Comment by metaphore** [comment]
I found the source of problem, it's a bug somewhere in a code that saves window's bounds upon application close. It may take some time till the next release that will bring the fix, so for anyone who faced the same situation quick solution is **delete this file and all should back to normal `C:\Users\<username>\.gdxtexturepackergui\window_params.xml`**
