### ISSUE TITLE
Cannot change language to Chinese 

### ISSUE THREAD

**Issue by ocd-lab** [crashinvaders/gdx-texture-packer-gui#116]
Can not change language as Chinese even if I install the CJK font
![image](https://user-images.githubusercontent.com/79586594/132958764-af90ea8d-de58-4537-ac0c-9dc0de201e93.png)
![image](https://user-images.githubusercontent.com/79586594/132958783-5f30a815-5386-4063-9aa1-4dc735a7d41f.png)

**Comment by metaphore** [comment]
Hi there, thanks for the report.
So basically when you click on the Chinese item in the language drop down list - nothing happens?

Which version are you on (can be displayed from Help>About menu)?

**Comment by ocd-lab** [comment]
Hi this is version
![image](https://user-images.githubusercontent.com/79586594/132972411-590c5be6-add6-4b1a-8ea4-f5d91140d3dd.png)

**Comment by metaphore** [comment]
Sorry for the late reply.

The version can be displayed from within the internal main menu panel. Please check on the screenshots and let me know which one do you have.

![image](https://user-images.githubusercontent.com/6159734/135746883-b8de5750-04cc-4cfe-974d-665f06e09617.png)

![image](https://user-images.githubusercontent.com/6159734/135746907-e560224f-2b16-41c3-ac2b-416106c4c426.png)

Besides that, do you actually have a crash or just nothing happens when you click on the Chinese language item from the menu?

**Comment by metaphore** [comment]
@ocd-lab could you please check if the language changes fine in the [4.10.1](https://github.com/crashinvaders/gdx-texture-packer-gui/releases/tag/4.10.1) release?

**Comment by metaphore** [comment]
The issue must be fixed by the time [4.11.0 is out](https://github.com/crashinvaders/gdx-texture-packer-gui/releases/tag/4.11.0). Feel free to reopen if the problem still stands.
