### ISSUE TITLE
Is the macOS version  in your plan ?

### ISSUE THREAD

**Issue by finscn** [crashinvaders/gdx-texture-packer-gui#12]
The LibGDX is cross platform , I hope gdx-texture-packer-gui could do it too.

Thanks.

**Comment by metaphore** [comment]
It does work on macOS. Just download regular [zip distribution](https://github.com/crashinvaders/gdx-texture-packer-gui/releases/download/4.3.1/gdx-texturepacker-4.3.1.zip) and you can run application by launching `.jar` file.

Since we have Windows installer, it's reasonable to add package distributions for Mac and Linux as well. I'm currently working on it and next version should get at least `.dmg` file.

**Comment by metaphore** [comment]
Done. Simple `.dmg` file now will be shipped with every distribution.
