### ISSUE TITLE
Adding directories won't work

### ISSUE THREAD

**Issue by allrod5** [crashinvaders/gdx-texture-packer-gui#20]
Adding a directory as input for a pack rather than selecting individual files won't work.

Version: 4.5.0
OS: Ubuntu 16.04 LTS

Steps to reproduce:

1. Have some .pngs on a folder, say _sprites_
2. Create a new pack
3. Click to "Add input files" and select _sprites_ folder
4. Click to Pack

This error log will be presented:

> Packing is started
> [output-red]Exception occurred:[] No images to pack
> [output-red]Stack trace:[] 
> java.lang.IllegalStateException: No images to pack
> 	at com.crashinvaders.texturepackergui.controllers.packing.processors.PackingProcessor.performPacking(PackingProcessor.java:41)
> 	at com.crashinvaders.texturepackergui.controllers.packing.processors.PackingProcessor.processPackage(PackingProcessor.java:31)
> 	at com.crashinvaders.texturepackergui.utils.packprocessing.CompositePackProcessor.processPackage(CompositePackProcessor.java:20)
> 	at com.crashinvaders.texturepackergui.utils.packprocessing.PackProcessingManager$1.run(PackProcessingManager.java:58)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)

PS.: Adding a folder as input for the pack will work fine under Aurelien Ribon's v3.2.0.

I would like to move on from v3.2.0, but selecting each PNG by hand and editing the regions names to match the directory structure is a no go for me.

Hope you will be able to fix this :) By the way the new GUI looks great, congrats!

**Comment by metaphore** [comment]
Hm, it looks like a specific case bug, because I believe no one has this problem on a regular basis, at least I have this working correct on my Lubuntu 16.10 and have never met behavior like this. I will definitely need some more info to reproduce it. Can you please provide me with the next info:
1. What is exact directory path (input file)? 
2. Are you sure directory contains legit `.png` files inside and not in a subdirs? Because application only looks for `.png`, '.jpg' and '.jpeg' file extensions inside of every specified dir and the error you have is a sign of app cannot find any.

PS: Input file list is a feature introduced only in the latest update (`4.4.0`) and I expect it may contain several bugs here and there. But in case if you need more stable version that works properly with input dir right now, I would recommend to downgrade to the [previous release (`4.3.2`)](https://github.com/crashinvaders/gdx-texture-packer-gui/releases/tag/4.3.2), it provides same old way packing functionality as Aurelien's application.

**Comment by allrod5** [comment]
@metaphore Great to hear that. Indeed my directory has subdirs within subdirs before getting to the PNGs. The full path contain spaces in directory names, but I think that it is not a cause of bugs, especially under Linux.

**Comment by tommyettinger** [comment]
I also just hit this bug when updating to 4.4.0. I'm downgrading to 4.3.2, which never had this bug, because there is no way I could add all the subfolders by hand.

**Comment by metaphore** [comment]
It appears to me like just a lack of recursive files inclusion. I'm going to add this flag to the input dir properties dialog in the next version.

**Comment by metaphore** [comment]
I added `recursive` and `flatten paths` flags per input dir entry. This should help manage input structures where images located at the different levels inside directory. One note here: unless it was made in previous versions, `recursive` flag means for what it stands - full recursive inclusion and not only one level below specified directory.

![image](https://cloud.githubusercontent.com/assets/6159734/26750255/02c92a04-4848-11e7-98a1-139594dc459f.png)
