### ISSUE TITLE
Nine Patch Editor - Preview

### ISSUE THREAD

**Issue by RUSshy** [crashinvaders/gdx-texture-packer-gui#27]
Hi, i thinking about preview for nine patch editor, hard to know how it'll render, so preview would help a lot

also is possible to make nine patch editor from atlas directly? like we select an region from atlas view and we can edit that

but that means u need be able to edit .atlas file, so need project model change to internally handle .atlas, wich sounds complicated, have you think about that already?

thanks!

**Comment by metaphore** [comment]
Yeah, nine patch editor is a very raw tool now that should be extended at least with preview of course. I'm going to work on it for the next update.

Atlas preview now is a kind of a cheap trick and is only loaded image/data from already packed atlas. It would be great of course to have a real pre-packed atlas inspection tool, where every region on canvas will dynamically response to changes you make in atlas configuration, but from what I see there is a ton of a work should be made for it and I'm sorry to say but I don't think it worth that much efforts give that much benefits overall, at least for now because there are some other important features can be implemented. So if you have any ideas on how to improve current post-packed preview, I would be happy to discuss.

**Comment by metaphore** [comment]
@RUSshy and it's done!

![Alt Text](https://i.imgur.com/uSNPcXL.gif)

**Comment by raeleus** [comment]
Looks great! This is definitely my go to now for nine patch editing.
