### ISSUE TITLE
Prompt to Save Project Upon Exit

### ISSUE THREAD

**Issue by raeleus** [crashinvaders/gdx-texture-packer-gui#34]
It would be nice to be prompted to save changes when exiting the program. Blame it on a lack sleep, but I've been forgetting to save lately. Then I spend time trying to figure just what the hell I did to break my games. Thanks!

**Comment by metaphore** [comment]
Oh, sorry about that, but I left exit logic without any prompt on purpose for a good thing actually ... or maybe because I just was lazy :)
The thing is right now the app doesn't have a code to check if any real changes were made to the project and I saved this task for a later. I though it could be annoying to always close usually redundant prompt before any exit. Well anyway, it's a good time to finally bring changes detector to the stage, I will include it in the next update.
