### ISSUE TITLE
Ability to set offsets to sprites.

### ISSUE THREAD

**Issue by gnFur** [crashinvaders/gdx-texture-packer-gui#37]
It'd be nice to be able to set sprite centers right in the packer.

**Comment by metaphore** [comment]
Unless `LibGDX` adds support for loading origin right from the texture atlas, it's not possible. But there is simply no reason for them to do so, as original `TexturePacker` classes are written with simplicity in mind and should be configured without any visual representation at all. So simple questions is no, at least for now.

**Comment by gnFur** [comment]
The packer can be used not only for libGDX. Me, for example, plan to use it with Monogame. And, imo, this feature is essential, at least as an option. I don't really understand why it should be thrown away.

**Comment by raeleus** [comment]
What Metaphore is saying is that this program is just a wrapper around LibGDX's texture packer code. Adding the feature you are requesting would require modifying that code and possibly breaking compatibility with existing LibGDX games. I don't see that as a feasible option. He isn't throwing your idea away.

**Comment by gnFur** [comment]
Storing an additional list of offsets and then doing a second pass writing these offsets to a GDX-generated file. Yeah, sounds, impossible.
And also, GDX generates an offset field for every sprite, so shouldn't there be a support for them already?

**Comment by raeleus** [comment]
Impossible seems a bit unfair. Maybe inappropriate would be my opinion.

The offset field is for a different purpose. When remove whitespace is turned on, this field is used to keep track of how much space was removed so the image can be reproduced properly in the game: https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/g2d/TextureAtlas.AtlasRegion.html

I prefer keeping my offsets separate from the textures and tied to my entities. A character may wear his hat in a different spot for example. I use Spine, so I don't have to worry about this anymore. However, a simple program that you can write for your own purposes is best suited for this need. I envision an entity editor that not only let's you set offsets for your textures, but also add data such as character name, health, etc. Exports to JSON. It sounds like a fun project. I would write it myself if I wasn't so busy.

**Comment by gnFur** [comment]
Oh, ok then.

**Comment by metaphore** [comment]
@gnFur please consider the fact that this project aims to support only default LibGDX atlas loader and doesn't provide any extended properties for an exported atlas file, yet. Also, it's important to say that features like this require some sort of a custom editor dialog implementation, otherwise extra simple text field doesn't make any sense, because it's not much different from appending text by hand to an exported file.

It worth mention, that I actually have some raw ideas on how to make this project support generic or at least few more engines. But for now, this more of a just thoughts and I have no plans to work in this direction in a near feature.
