### ISSUE TITLE
High DPI Support

### ISSUE THREAD

**Issue by Hangman** [crashinvaders/gdx-texture-packer-gui#39]
The UI is pretty small on a 4k screen.
My system scaling is set to 200% - so it should look the same as on 1080p displays.

**Comment by metaphore** [comment]
Good call, UI scaling is something the app is really missing. One thing though, due to implemention, it's fairly easy to just scale up all graphics, but not really support textures for another resolution, but the approach should be just fine for now. Also, I'm not sure that system UI scaling value is available to Java process that easy, so the setting should be changed only manually.

**Comment by Hangman** [comment]
I'm not sure about LWJGL2 backend, but version 3 seems to provide access to the system scaling value.
[https://github.com/libgdx/libgdx/wiki/Querying-%26amp%3B-configuring-graphics-%28monitors%2C-display-modes%2C-vsync%29](url)

If not... a button to toggle hdpi mode would do the job as well :)

**Comment by metaphore** [comment]
Thanks, will look if I can access system scaling somehow to apply UI scaling automatically.

**Comment by Hangman** [comment]
!!! Thank you so much, this change helps a lot.

**Comment by metaphore** [comment]
BTW, what is OS you're on?

**Comment by Hangman** [comment]
I'm on Win10 with 200% scaling.

**Comment by metaphore** [comment]
I have 125% scaling set for one of my monitors and still cannot make the window to ignore system scaling. So you're saying that texture packer window appears to be tiny and pixel perfect on your side? What's JRE you're running?

**Comment by Hangman** [comment]
This is how it looks like on my screen. My JRE is of version 9.0.4.

1920*1080 on 100% scaling
![1080](https://user-images.githubusercontent.com/108926/38780213-6205e60e-40d3-11e8-8d7c-0e62aaab6c1a.png)

3840*2160 on 200% scaling
![4k](https://user-images.githubusercontent.com/108926/38780214-621e464a-40d3-11e8-9aea-038fe1c7d24f.png)

**Comment by metaphore** [comment]
Oh, it's a bit different case, the bug in GLHF that I've mentioned. It was about that GLHF can't recognize system scaling values properly and as a result sets wrong viewport configuration. Unfortunately, this will only get fixed in LibGDX 1.9.9, and in order to apply the fix, we have to wait for the official release, I hope this will happen some time soon.

Anyway, I believe interface scaling at least will let you upscale UI a little to have at least readable content for now.
