### ISSUE TITLE
[Report] just opened app

### ISSUE THREAD

**Issue by EtK2000** [crashinvaders/gdx-texture-packer-gui#53]
open app, it crashed
windows 10, i3 550, no gpu, 4GB RAM DDR2

<details><summary>Application log</summary>

```

```

</details>

This issue is related to Java 8 and Windows 10 Intel Drivers.
Rolling back to Java 8u51 works.

**Comment by metaphore** [comment]
Could you please share any details or give a link to a page where someone describes the problem and the solution? Thanks.

**Comment by EtK2000** [comment]
Here's an example:
https://github.com/LWJGL/lwjgl/issues/119

**Comment by EtK2000** [comment]
I think you should catch this Exception and show a message instead of crashing.

**Comment by metaphore** [comment]
@EtK2000 if that's still an issue, can you please give an example of how exception looks like?

**Comment by tommyettinger** [comment]
From what I can tell from that LWJGL issue page, it isn't a Java-accessible Exception that can be caught, and the best solution for @EtK2000 would be to use one of the patches for their system here https://github.com/pal1000/save-legacy-intel-opengl . I'm glad that there's at least some support out there for such old hardware, but at some point the solution becomes "install Linux next to or over Windows 10, because Microsoft won't care about this era of machine."

**Comment by EtK2000** [comment]
I can catch the Exception in my LibGDX project as follows:
```java
Thread.setDefaultUncaughtExceptionHandler((t, e) -> {
	Throwable tc = e;
	while (tc.getCause() != null && tc.getCause() != tc)
		tc = tc.getCause();

	// check for Windows 10 Java issue
	if (tc.getMessage() != null) {
		if (tc.getMessage().contains("OpenGL 2.0 or higher with the FBO extension is required")) {
			String[] ver = System.getProperty("java.version").split("\\.");
			if (ver[1].compareTo("8") > -1 && ver[1].compareTo("0_60") > -1 && System.getProperty("os.version").equals("10.0"))
				;// old graphics card on windows 10 issue
			else
				;// just a regular old graphics card
		}
	}
	// do something with the exception
});
```

**Comment by tommyettinger** [comment]
Does updating the Java 8 version help at all (or updating to Java 11)? It looks like Zulu's builds of OpenJDK may use a different numbering scheme, and are at 8u181 for the latest Java 8 version. https://www.azul.com/downloads/zulu/zulu-windows/ I'm not sure, but the check with `ver[1].compareTo("0_60")` might be incorrect if the version is `"0_181"`. Still, if it's true that "OpenGL 2.0 or higher with the FBO extension is required" and your graphics drivers don't satisfy that requirement, what should this application do when it catches that Throwable? A GUI window for a message would need to use AWT/Swing instead of the existing LWJGL user interface, because LWJGL would keep throwing that Throwable. If the application is a jar file and was double clicked, it won't have a terminal to print to by default on Windows (double clicking uses javaw.exe, which does not pop up a cmd.exe instance, while java.exe would). It sounds like this isn't an issue with this repo's code, but rather with driver support on your machine or compatibility bugs in the JDK. There's also the possibility that OpenJ9, an alternative compiler open-sourced by IBM, might not have the same compatibility bug: https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9 (I just ran this app on Windows 7 with OpenJ9 version 11 and with the older IBM J9 version 8, and it seems to run fine.) Maybe try some other Java versions if this is still an issue? In particular, if OpenJ9 doesn't have this issue on Windows 10 (IBM has said they will support Java 8 for a long time, and that may include older Java on older hardware), that might be good to know, so any bundles of this application could include that JDK instead of OpenJDK. The Adopt OpenJDK project makes OpenJ9 easy to install now, and that wasn't always the case. If any form of Java 11 works, this project can probably distribute a minimized JRE using jlink, which would save some download time, and would guarantee a specific Java version.

**Comment by EtK2000** [comment]
Getting it to work isn't an issue, I can use java 8u51 and it works.
I'm just saying this exception should be caught, and a simple Swing dialogue can open telling the user.

**Comment by metaphore** [comment]
The app has been recently updated to LWJGL3 in the [4.9.0](https://github.com/crashinvaders/gdx-texture-packer-gui/releases/tag/4.9.0) release and the problem might be solved in there. Can anyone confirm it's still the case?

**Comment by metaphore** [comment]
As it's a pretty old and seemingly environment-specific bug, I'm gonna close it. If anyone has any issues related to the topic, feel free to reopen.
