### ISSUE TITLE
Texture packer does not take 9-Patch content area into account

### ISSUE THREAD

**Issue by estebes** [crashinvaders/gdx-texture-packer-gui#62]
When creating a 9-Patches for a ProgressBarStyle I noticed that the content area defined in my 9-Patches was not being taken into account.
9-Patch:
![patch](https://user-images.githubusercontent.com/6414656/50277903-94f34d80-043d-11e9-89db-23e3d8d05659.png)
![content](https://user-images.githubusercontent.com/6414656/50277905-96bd1100-043d-11e9-94f9-b8d8ccb27e63.png)
Generated atlas code:
![wrong_code](https://user-images.githubusercontent.com/6414656/50277944-b94f2a00-043d-11e9-9f96-2a167669c663.png)
End result:
![wrong](https://user-images.githubusercontent.com/6414656/50277870-8016ba00-043d-11e9-8939-dc95ebeadcaa.png)

I need to manually add a pad setting into the atlas everytime I pack it:
![added](https://user-images.githubusercontent.com/6414656/50278013-d552cb80-043d-11e9-8eac-5b7e67d79558.png)
End result:
![end](https://user-images.githubusercontent.com/6414656/50278052-ec91b900-043d-11e9-90b7-e8bf1b69390c.png)

**Comment by metaphore** [comment]
Sorry for the late reply and thanks for the report.
I just checked the same case on my end and `pad` values appear to be fine (4.8.1 version).

```
input0
  rotate: false
  xy: 2, 2
  size: 24, 12
  split: 6, 6, 7, 4
  pad: 0, 0, 0, 0
  orig: 24, 12
  offset: 0, 0
  index: -1
```

Which version are you on?
Also in case you're on the latest one (4.8.1), could you please send me a sample project where you experience such a bug?

Here is the one I used to test the output, please try it and let me know if the pad values are also missing in the packed atlas - [9patch-test.zip](https://github.com/crashinvaders/gdx-texture-packer-gui/files/2718065/9patch-test.zip)

**Comment by estebes** [comment]
Thanks for the reply. I'm using version 4.8.1.
Tested with your textures and the same thing happens. If the content pad is different than 0 it is added in the packed atlas. If it is 0 it is not.
Output with pad of 1:
```
input0
  rotate: false
  xy: 36, 6
  size: 24, 12
  split: 5, 5, 0, 12
  pad: 1, 1, -1, -1
  orig: 24, 12
  offset: 0, 0
  index: -1
```
Output with pad of 0:
```
input0
  rotate: false
  xy: 36, 6
  size: 24, 12
  split: 5, 5, 0, 12
  orig: 24, 12
  offset: 0, 0
  index: -1
```

**Comment by estebes** [comment]
I use .9.pngs and I did not change anything. Using exactly what you sent me works but you are using a regular png and not a 9.png
Output:
```
input0
  rotate: false
  xy: 2, 2
  size: 24, 12
  split: 6, 6, 7, 4
  pad: 0, 0, 0, 0
  orig: 24, 12
  offset: 0, 0
  index: -1
```

**Comment by metaphore** [comment]
Ah right, I see the issue now. Pad values get not correctly extracted from `.9.png` files.

In this particular case, the pad values should be equal to the split values as they are not defined explicitly, but for some reason the application treats them as `0, 0, 0, 0` and omits in the export.

![image](https://user-images.githubusercontent.com/6159734/50558273-15a82880-0d1f-11e9-99b4-de2a6f95bfd0.png)

![image](https://user-images.githubusercontent.com/6159734/50558296-70418480-0d1f-11e9-8454-6797b2b2aeff.png)

**Comment by estebes** [comment]
Yes that is it. Sorry. It was a little hard to explain.

**Comment by metaphore** [comment]
Here is the updated version, please check it out and confirm that it works fine. Now for the specific case (described above) 9-patch editor will display correct pad values. 

But keep in mind, this won't give you expected behavior, as if you don't put any pixels on the right and bottom line of `.9.png` it means the _pad_ values are equal to the _split_ values (that's why there is no pad in the output for your case). 

If you don't use the same `.9.png` image in multiple atlases, I would recommend to keep them as simple `.png` in file system and then define 9-patch properties using the editor withing the app (you can turn a regular image into 9-patch by clicking on the check box on properties window). Or change the pad values for the original `.9.png` image in the updated version of the app, that should work too.

![image](https://user-images.githubusercontent.com/6159734/50559038-818d8f80-0d25-11e9-8a3f-20ffd72bab7a.png)

[gdx-texturepacker-4.8.2.zip](https://github.com/crashinvaders/gdx-texture-packer-gui/files/2718199/gdx-texturepacker-4.8.2.zip)

**Comment by estebes** [comment]
Thank you very much. Using the 9-patch properties editor does what I want. Happy new year.
