### ISSUE TITLE
Image files get deleted

### ISSUE THREAD

**Issue by Betalord** [crashinvaders/gdx-texture-packer-gui#65]
I've just noticed a most annoying bug:
I've chosen export file as "status.atlas".
In the same folder, I had files named "status0.png", "status1.png", "status2.png".
When I clicked on "pack", all three of the png files would get deleted and program would throw an exception (which it caches and reports in a log window).

This bug needs fixing, of course.

**Comment by metaphore** [comment]
Yes, that should happen because this is how pre-packing cleanup works, it deletes all image files matching atlas name pattern. Although it may look broken, fixing this part wont actually change much - during the packing procedure, the program will generate images using given atlas name and obviously will rewrite the other image files with the same name anyway.

I wouldn't really care much about the case, as it's hard to imagine why would anyone may want to export atlas to the directory containing source images. I think the compromise could be to introduce some sort of a warning/error message, to prevent source image loss.

**Comment by Betalord** [comment]
Actually, putting everything in the same folder makes much sense. I have an
EXPORT folder when I put all png files exported from Inkscape, including
atlas (and png) files exported from your program.
Perhaps my description wasn't clear enough: program deletes png files of
images that do not have the same name as exported png file, but SIMILAR
names. This is the real problem. It should simply delete (better:
overwrite) the same file name, not similar.

**Comment by metaphore** [comment]
Sorry for the late reply. As there's no tracking of the previous exports and exact files/configuration that was used to produce the export, the best the app can rely on to clean up the previous export is to simply match the files by the name. I can't think of any good and quick solution for the case explained. 

Until this specific case becomes a real problem for the large userbase, I don't think it's reasonable to come up with something sophisticated to fix it. For now, this must be considered as simply a program limitation and I'm afraid you have to work around it by using separate output folders.
