### ISSUE TITLE
KTX ETC2 format results in black image.

### ISSUE THREAD

**Issue by Trurl101** [crashinvaders/gdx-texture-packer-gui#71]
I tried to use the KTX format with etc2, but it just result in a black image. All other formats work fine.

Using texturepacker 4.8.2 with OSX.

<img width="1943" alt="Bildschirmfoto 2019-08-12 um 12 28 36" src="https://user-images.githubusercontent.com/1546629/62859218-d00ffd00-bcfc-11e9-907d-60cc48d9db32.png">

**Comment by metaphore** [comment]
Sorry for the late reply. The issue might be caused by the missing ETC2 GPU compression extension in the MacOS OpenGL driver. I will give it a try to see if that's the actual reason. But I guess besides the displaying problem in the texture packer, the actual texture should be packed correctly and is valid for any ETC2 compatible environment.

By chance did you try to use the output result in any Android LibGDX application?

**Comment by metaphore** [comment]
Ok, it's definitely related to macOS OpenGL support ETC1/ETC2 compression support (KTX is a container for those). The texture is actually compressed and valid, the only downside it cannot be natively shown on any macOS/iOS device. I will add some notice about that to the preview area for macOS users in the next release.
